[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solstream_contract = "9xoW3QTr4BjtJmGq2QN5mMyg96NP5TrVuZQZHbvkAVVi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
